lastname = "InmateLast" #
firstname = "Inmatefirst" #
admit = "Last Admission Date" #
age_book = "Age at booking" #
age = None #
DOB = None #
charge_desc = "ChargeDescription" #
statute = "Statute" #
charge_class = "ChargeCrimeType" #
city = "City" #
charge = "Standardized Description"
bond = "CurrentBond"
totalbond = "TotalBond"
days_in = "Days in Custody from Last Admission Date" #
zipcode = "Zip" #
charge_disp = "casedisposition" #
iid = "Inmateid" #
gender = "Gender" #
race = "Race" #
bid = "Bookingid"

def bond_denied(data):
    if data == 0:
        return True
    else:
        return False

race_dict = None

city_dict = {
    None: {'INDIANA', 'IL', 'MINNESOTA', 'N', '.'},
    'ADDISON': {'ADDISON'},
    'ALSIP': {'ALSIP'},
    'ALTAMONTE': {'ALTAMONTE'},
    'ANDERSON': {'ANDERSON'},
    'ANTIOCH': {'ANTIOCH'},
    'APPLE VALLY': {'APPLE VALLY'},
    'APPLETON': {'APPLETON'},
    'ARLINGTON HEIGHTS': {'ARLINGTON HEIGHTS'},
    'ATOMA': {'ATOMA'},
    'ATWATER': {'ATWATER'},
    'AURORA': {'AURORA'},
    'AUSTIN': {'AUSTIN'},
    'BARRINGTON': {'BARRINGTON'},
    'BARTLETT': {'BARTLETT'},
    'BATAVIA': {'BATAVIA'},
    'BEACH PARK': {'BEACH PARK'},
    'BEECHER': {'BEECHER'},
    'BELLWOOD': {'BELLWOOD', 'BELWOOD', 'BELLWOD'},
    'BELVIDERE': {'BELVIDERE'},
    'BENSENVILLE': {'BENSENVILLE', 'BENSONVILLE'},
    'BERKELEY': {'BERKLEY', 'BERKELEY'},
    'BERRIEN SPRINGS': {'BERRIEN SPRINGS'},
    'BERWYN': {'BERWIN', 'BERWYN', 'BERWWYN', 'BERYWN'},
    'BEVERLY': {'BEVERLY'},
    'BLOOMINGDALE': {'BLOOMINGDALE'},
    'BLOOMINGTON': {'BLOOMINGTON'},
    'BLUE ISLAND': {'BLUE  ISLAND', 'BLUE ISLAND', 'BLUEISLAND'},
    'BOLINGBROOK': {'BOLINGBROOK', 'BOLLINGBROOK'},
    'BOULDER': {'BOULDER'},
    'BOURBONNAIS': {'BOURBONNAIS'},
    'BRAIDWOOD': {'BRAIDWOOD'},
    'BREWTON': {'BREWTON'},
    'BRIDGEVIEW': {'BRIDGVIEW', 'BRIDEGVIEW', 'BIRDGEVIEW', 'BRIDGEVIEW'},
    'BROADVIEW': {'BOARDVIEW', 'BROADVIEW'},
    'BROOKFIELD': {'BROOKFEILD', 'BROOKFIELD'},
    'BROOKLYN': {'BROOKLYN'},
    'BROOKLYN CENTER': {'BROOKLYN CENTER'},
    'BUFFALO': {'BUFFALO'},
    'BUFFALO GROVE': {'BUFFALO GROVE'},
    'BURBANK': {'BURBANK'},
    'BURLINGTON': {'BURLINGTON'},
    'BURNHAM': {'BURNHAM'},
    'BURR RIDGE': {'BURR RIDGE'},
    'CALUMET CITY': {'CAL CITY', 'CALUMET', 'CALUMET CITY', 'CALUMET  CITY'},
    'CALUMET PARK': {'CALUMET PARK', 'CALUMET PK'},
    'CAMPBELLVILLE': {'CAMPBELLVILLE'},
    'CAROL STREAM': {'CAROL STREAM'},
    'CARPENTERSVILLE': {'CARPENTERVILLE', 'CARPENTERSVILLE'},
    'CARY': {'CARY'},
    'CAULMET  CITY': {'CAULMET  CITY'},
    'CEDAR LAKE': {'CEDAR LAKE'},
    'CEDAR POINT': {'CEDAR POINT'},
    'CEDAR RAPIDS': {'CEDAR RAPIDS'},
    'CHAMPAIGN': {'CHAMPAIGN'},
    'CHANNAHON': {'CHANNAHON'},
    'CHARLOTTE': {'CHARLOTTE'},
    'CHICAGO': {   '60623',
                   'ACHI',
                   'C',
                   'CCHICAGFO',
                   'CGHICAGO',
                   'CGHO',
                   'CGO',
                   'CHCAGO',
                   'CHCIAGO',
                   'CHCIGO',
                   "CHCIGOCHICAGO'",
                   'CHFO',
                   'CHG',
                   'CHGFO',
                   'CHGIAGO',
                   'CHGIO',
                   'CHGO',
                   'CHGO  RDGE',
                   'CHGOC',
                   'CHHIC',
                   'CHI',
                   'CHI CAGO',
                   'CHIACAGO',
                   'CHIACGO',
                   'CHIAGO',
                   'CHIC',
                   'CHICADO',
                   'CHICAG',
                   'CHICAG0',
                   'CHICAGHO',
                   'CHICAGI',
                   'CHICAGO',
                   "CHICAGO'",
                   'CHICAGOI',
                   'CHICAGOL',
                   'CHICAGOP',
                   'CHICAGO`',
                   'CHICAGP',
                   'CHICAHO',
                   'CHICAO',
                   'CHICAOG',
                   'CHICCAGO',
                   'CHICGAO',
                   'CHICGO',
                   'CHICSGO',
                   'CHIGAGO',
                   'CHIICAGO',
                   'CHIO',
                   'CHIOC',
                   'CHOCAGO',
                   'CJICAGO',
                   'GHGO',
                   '`CHICAGO'},
    'CHICAGO HEIGHTS': {   'CHGO HEIGHTS',
                           'CHGO HGTS',
                           'CHGO HTS',
                           'CHGO M HGTS',
                           'CHGO. HGTS.',
                           'CHGOHGTS',
                           'CHICAGO  HEIGHTS',
                           'CHICAGO HEIGHTS',
                           'CHICAGO HGTS',
                           'CHICAGO HGTS.',
                           'CHICAGO HIEGHTS',
                           'CHICAGO HIGHTS',
                           'CHICAGO HTS',
                           'SO CHICAGO HGTS.'},
    'CHICAGO RIDGE': {'CHICAGO RIDGE'},
    'CICERO': {'CICERO', 'CICEROO'},
    'CINCINATTI': {'CINCINATTI'},
    'CLEVELAND': {'CLEVELAND'},
    'CLINTON': {'CLINTON'},
    'COAL VALLEY': {'COAL VALLEY'},
    'COUNTRY CLUB': {'COUNTRY CLUB'},
    'COUNTRY CLUBS HILLS': {   'COCNTRY CLUB HILLS',
                               'COUNTRY CLUB HILL',
                               'COUNTRY CLUB HILLS',
                               'COUNTRY CLUBS HILLS',
                               'COUNTY CLUBS HILLS'},
    'COUNTRYSIDE': {'COUNTRYSIDE'},
    'CREST HILL': {'CREST HILL', 'CRESTHILL'},
    'CRESTWOOD': {'CRESTWOOD'},
    'CRETE': {'CRETE'},
    'CROWN POINT': {'CRONW POINT', 'CROWN POINT'},
    'CRYSTAL FALLS': {'CRYSTAL FALLS'},
    'CRYSTAL LAKE': {'CRYSTAL LAKE'},
    'DALLAS': {'DALLAS'},
    'DARIEN': {'DARIEN'},
    'DAYTON': {'DAYTON'},
    'DEKALB': {'DEKALB'},
    'DEMOTT': {'DEMOTT'},
    'DENVER': {'DENVER'},
    'DES PLAINES': {   'DES PLAIN',
                       'DES PLAINES',
                       'DES PLAINS',
                       'DESPLAINES',
                       'DESPLAINS'},
    'DESMONDES': {'DESMONDES'},
    'DIXMOOR': {'DIXMORE', 'DIXMOOR', 'DIXMOORE'},
    'DIXON': {'DIXON'},
    'DOLTON': {'DOLTON', 'DOLTOM'},
    'DOWNERS GROVE': {'DOWNERS GROVE'},
    'EAST CHICAGO': {'E CHCGO', ' CHGO', 'EAST CHICAGO'},
    'EAST DUNDEE': {'EAST DUNDEE'},
    'EAST HAZEL CREST': {'EAST HAZEL CREST'},
    'EAST MOLINE': {'EAST MOLINE'},
    'EDGEMONT': {'EDGEMONT'},
    'EGV': {'EGV'},
    'EL PASO': {'EL PASO'},
    'ELBURN': {'ELBURN'},
    'ELGIN': {'ELGIN'},
    'ELK GROVE': {'ELK GROVE'},
    'ELK GROVE VILLAGE': {'ELK GROVE VILLAGE'},
    'ELMHURST': {'ELMHURST'},
    'ELMWOOD PARK': {'ELMWOOD PARK'},
    'ELWOOD': {'ELWOOD'},
    'EVANSTON': {'EVENSTON', 'EVANSTON'},
    'EVANSVILLE': {'EVANSVILLE'},
    'EVERGREEN': {'EVERGREEN'},
    'EVERGREEN PARK': {'EVERGREEN PARK', 'EVERGREEN PK', 'EVERGRENN PARK'},
    'FAIRVIEW HEIGHTS': {'FAIRVIEW HEIGHTS'},
    'FARGO': {'FARGO'},
    'FLOSSMOOR': {'FLOSSMOR', 'FLOSSMOOR', 'FLOSSMORE'},
    'FORD HEIGHTS': {   'FORD HEIGHTS',
                        'FORD HGTS',
                        'FORD HGTS.',
                        'FORD HIEGHTS',
                        'FORD HIGHTS',
                        'FORD HT',
                        'FORD HTS'},
    'FOREST PARK': {'FOREST PRK', 'FOREST PARK', 'FORREST PARK'},
    'FRANKFORT': {'FRANKFORT'},
    'FRANKLIN PARK': {'FRANKLIN [PARK', 'FRANKLIN  PARK', 'FRANKLIN PARK'},
    'FREEPORT': {'FREEPORT'},
    'GALESBURG': {'GALESBURG'},
    'GALESBURGES': {'GALESBURGES'},
    'GARY': {'GARY'},
    'GENOA': {'GENOA'},
    'GIG HARBOR': {'GIG HARBOR', 'GIGHARBOR'},
    'GLEN ELLEN': {'GLEN ELLEN'},
    'GLENDALE HEIGHTS': {'GLENDALE HEIGHTS', 'GLENDALE HTS'},
    'GLENVIEW': {'GLENVIEW'},
    'GLENWOOD': {'GLENWOOD', 'GELNWOOD'},
    'GRACELAKE': {'GRACELAKE'},
    'GRAND RAPIDS': {'GRAND RAPIDS'},
    'GREEN BAY': {'GREEN BAY', 'GREENBAY'},
    'GREENVILLE': {'GREENVILLE'},
    'GRIFFITH': {'GRIFFITH'},
    'GURNEE': {'GURNEE'},
    'HAMMOND': {'HAMMOND', 'HAMMAND'},
    'HANOVER PK': {'HANOVER PK', 'HANOVER PARK'},
    'HARVEY': {'HARVE', 'HARVEY'},
    'HARWOOD HEIGHTS': {'HARWOOD HTS', 'HARWOOD HEIGHTS'},
    'HAWTHORNE WOODS': {'HAWTHORNE WOODS'},
    'HAZEL CREST': {'HAZELCREST', 'HAZEL CREST', 'HAZAELCREST', 'HAZLECREST'},
    'HENDERSONVILLE': {'HENDERSONVILLE'},
    'HICKORY HILLS': {'HICKORY HILLS'},
    'HIGHLAND PARK': {'HIGHLAND PARK'},
    'HILLSIDE': {'HILLSIDE'},
    'HINSDALE': {'HINSDALE'},
    'HOBART': {'HOBART'},
    'HODGKINS': {'HODGKINS'},
    'HOFFMAN ESTATES': {'HOFFMAN ESTATE', 'HOFFMAN ESTATES'},
    'HOLLAND': {'S HOLLAND', 'HOLLAND'},
    'HOMELESS': {'HOMELESS'},
    'HOMER GLEN': {'HOMER GLEN'},
    'HOMETOWN': {'HOMETOWN'},
    'HOMEWOOD': {'HOMEWOOD'},
    'HOWARD': {'HOWARD'},
    'HUNTLEY': {'HUNTLEY'},
    'INDIAN HEAD PARK': {'INDIANHEAD PARK', 'INDIAN HEAD PARK'},
    'INDIANAPOLIS': {'INDIANAPOLIS'},
    'INGLESIDE': {'INGLESIDE'},
    'IOWA CITY': {'IOWA CITY'},
    'IRVING': {'IRVING'},
    'ITASCA': {'ITASCA'},
    'JACKSON': {'JACKSON'},
    'JERUCO': {'JERUCO'},
    'JOHNSON CITY': {'JOHNSON CITY'},
    'JOLIET': {'JOILET', 'JOLIET'},
    'JUSTICE': {'JUSTIC', 'JUSTICE'},
    'KALMAZOO': {'KALMAZOO'},
    'KANKAKEE': {'KANKAKEE'},
    'KENOSHA': {'KENOSHA'},
    'KEY WEST': {'KEY WEST'},
    'KILDEER': {'KILDEER'},
    'KOKOMO': {'KOKOMO'},
    'KOSCIUSKO': {'KOSCIUSKO'},
    'LA GRANGE PARK': {'LA GRANGE PARK'},
    'LAFAYETTE': {'LAFAYETTE'},
    'LAGRANGE': {'LAGRANGE'},
    'LAKE VILLA': {'LAKE VILLA'},
    'LAKE ZURICH': {'LAKE ZURICH'},
    'LANSING': {'LANSING', 'LANCING'},
    'LARNED': {'LARNED'},
    'LAS VEGAS': {'LAS VEGAS'},
    'LAURENCEVILLE': {'LAURENCEVILLE'},
    'LEMONT': {'LEMONT'},
    'LEWISVILLE': {'LEWISVILLE'},
    'LEYDEN': {'LEYDEN'},
    'LINCOLNSHIRE': {'LINCOLSHIRE', 'LINCOLNSHIRE'},
    'LINCOLNWOOD': {'LINCOLNWOO', 'LINCOLNWOOD'},
    'LISLE': {'LISLE'},
    'LOCKPORT': {'LOCKPORT'},
    'LOGAN': {'LOGAN'},
    'LOGANSPORT': {'LOGANSPORT'},
    'LOMBARD': {'LOMBARD'},
    'LOS ANGELES': {'LOS ANGELES'},
    'LOUISVLLE': {'LOUISVLLE'},
    'LYNWOOD': {'LYNNWOOD', 'LYNWOOD'},
    'LYNWOOD IL': {'LYNWOOD IL'},
    'LYONS': {'LYON', 'LYONS'},
    'MADISON': {'MADISON'},
    'MARENGO': {'MARENGO'},
    'MARION': {'MARION'},
    'MARKHAM': {'MARKHAM'},
    'MATTESON': {'MATTESON', 'MATTSON', 'MATTSESON'},
    'MAYWOOD': {'MAYWOOD', 'MATWOOD', 'MAYW'},
    'MCHENEY': {'MCHENEY'},
    'MCHENRY': {'MCHENRY'},
    'MELROSE': {'MELROSE'},
    'MELROSE PARK': {   'MELROSE PARK',
                        'MELROSE PK',
                        'MELROSE PK.',
                        'MELROSE PRK'},
    'MENARD': {'MENARD'},
    'MERRIVILLE': {'MERRIVILLE'},
    'MIDLOTHIAN': {'MIDIOTHIAN', 'MIDLOTHIAN'},
    'MILWAUKEE': {'MILWAUKEE'},
    'MINOOKA': {'MINOOKA'},
    'MOKENA': {'MOKENA'},
    'MONEE': {'MONEE'},
    'MONONA': {'MONONA'},
    'MONTGOMERY': {'MONTGOMERY'},
    'MORAINE VALLEY': {'MORAINE VALLEY'},
    'MORGANTOWN': {'MORGANTOWN'},
    'MORRISTOWN': {'MORRISTOWN'},
    'MORTON GROVE': {'MORTIN GROVE', 'MORTON GROVE'},
    'MOUNT PROSPECT': {'MT. PROSPECT', 'MOUNT PROSPECT', 'MOUNT PROPECT'},
    'MOUNT VERNON': {'MOUNT VERNON'},
    'MUNDELINE': {'MUNDELINE'},
    'MUNSTER': {'MUNSTER'},
    'NAPERVILLE': {'NAPERVILLE'},
    'NASHIVILLE': {'NASHIVILLE'},
    'NEW LENOX': {'NEW LENOX'},
    'NILES': {'NILES'},
    'NORRIDGE': {'NORRIDGE'},
    'NORTH BARRINGTON': {'NORTHBARINGTON', 'NORTH BARRINGTON'},
    'NORTH CHICAGO': {'NORTH CHICAGO'},
    'NORTH RIVERSIDE': {'NORTH RIVERSIDE'},
    'NORTHBROOK': {'NORTHBROOKE', 'NORTHBROOK'},
    'NORTHLAKE': {'NORTH LAKE', 'NORTHLAKE'},
    'NORWOOD PK': {'NORWOOD PK'},
    'NOTHER RIVERSIDE': {'NOTHER RIVERSIDE'},
    'OAK BROOK': {'OAK BROOK'},
    'OAK FOREST': {'OAK FOREST', 'OAK  FOREST'},
    'OAK LAWN': {'OAK LAWN', 'OAKLAWN'},
    'OAK PARK': {'OAK PARK'},
    'OAKBROOK': {'OAKBROOK'},
    'OAKLAND': {'OAKLAND'},
    'OAKWOOD': {'OAKWOOD'},
    'OLYMPIA FIELDS': {'OLYMPIA FIELDS'},
    'ORLAND': {'ORLAND'},
    'ORLAND HILLS': {'ORLAND HILLS'},
    'ORLAND PARK': {'ORLAND PARK', 'ORLAND PK'},
    'OSWEGO': {'OSWEGO'},
    'OTTAWA': {'OTTAWA'},
    'PALATINE': {'PALANTINE', 'PALENTINE', 'PALATINE'},
    'PALOS HEIGHTS': {'PALOS HEIGHTS', 'PALOS HIGHTS'},
    'PALOS HILLS': {'PALOS HILL', 'PALOS HILLS'},
    'PALOS PARK': {'PALOS PARK'},
    'PARK FOREST': {'PARK FORST', 'PARK FORREST', 'PARK FOREST'},
    'PARK RIDGE': {'PK RIDGE', 'PARK RIDGE', 'PARKRIDGE'},
    'PEKIN': {'PEKIN'},
    'PEORIA': {'PEORIA'},
    'PEOTONE': {'PEOTONE'},
    'PETERSBURG': {'PETERSBURG'},
    'PHOENIX': {'PHOENIX', 'PHOENEX'},
    'PLACENTIA': {'PLACENTIA'},
    'PLAINEVILL': {'PLAINEVILL'},
    'PLAINFIELD': {'PLAINFIELD'},
    'POPULAR GROVE': {'POPULAR GROVE'},
    'PORTAGE': {'PORTAGE'},
    'POSEN': {'POSEN'},
    'PRINCETON': {'PRINCETON'},
    'PROSPECT HEIGHTS': {   'PROSPECT HEIGHTS',
                            'PROSPECT HGTS',
                            'PROSPECT HIEGHTS'},
    'PUEBLO': {'PUEBLO'},
    'RACINE': {'RACINE'},
    'RANTOUL': {'RANTOUL'},
    'RENSSELEAR': {'RENSSELEAR'},
    'RICHARDSON': {'RICHARDSON'},
    'RICHFIELD': {'RICHFIELD'},
    'RICHMOND': {'RICHMOND'},
    'RICHTON PARK': {'RICHTON PRK', 'RICHTON PARK', 'RICHTON PK'},
    'RIDGELY': {'RIDGELY'},
    'RIVER FOREST': {'RIVER FOREST'},
    'RIVER GROVE': {'RIVER GROVE', 'RIVERGROVE'},
    'RIVERDALE': {'RIVERDALE'},
    'RIVERSIDE': {'RIVERSIDE'},
    'ROBBINS': {'ROBBONS', 'ROBBINS'},
    'ROBIN': {'ROBIN'},
    'ROCHESTER': {'ROCHESTER'},
    'ROCHESTER HILLS': {'ROCHESTER HILLS'},
    'ROCKFORD': {'ROCKFORD'},
    'ROLLING MEADOWS': {'ROLLING MEADOWS'},
    'ROMEOVILLE': {'ROMEVILLE', 'ROMEOVILLE'},
    'ROSELLE': {'ROSELLE'},
    'ROSEMONT': {'ROSEMONT'},
    'ROUND LAKE': {'ROUND LAKE'},
    'SALINAS': {'SALINAS'},
    'SAME': {'SAME'},
    'SAN FRANCISCO': {'SAN FRANCISCO'},
    'SAN PIERRE': {'SAN PIERRE'},
    'SAUK VILLAGE': {   'SAUK VILLAGE',
                        'SAUK VILLIAGE',
                        'SAUL VILLAGE',
                        'SAULK VILLAGE',
                        'SAULK VILLIGE'},
    'SCHAUMBURG': {'SCHAUMBURG', 'SCHAUMBERG'},
    'SCHILLER PARK': {'SCHILLER PK.', 'SCHILLER PARK'},
    'SHANIHAN': {'SHANIHAN'},
    'SHEBION': {'SHEBION'},
    'SHOREWOOD': {'SHOREWOOD'},
    'SHREVEPORT': {'SHREVEPORT'},
    'SKOKIE': {'SKOKIE'},
    'SOUTH BEND': {'SOUTH BEND'},
    'SOUTH CHGO HTS': {'SOUTH CHGO HTS'},
    'SOUTH CHICAGO': {'SOUTH CHICAGO', 'SO CHICAGO'},
    'SOUTH CHICAGO HEIGHTS': {'SO CHICAGO HEIGHTS', 'SOUTH CHICAGO HEIGHTS'},
    'SOUTH ELGIN': {'SOUTH ELGIN'},
    'SOUTH HOLLAND': {'SOUTH HOLLAND', 'SOUTH HOLLAN'},
    'SPRING HILL': {'SPRING HILL'},
    'SPRINGFIELD': {'SPRINGFIELD'},
    'ST CHARLES': {'ST CHARLES', 'ST. CHARLES'},
    'ST LOUIS': {'ST LOUIS', 'ST. LOUIS'},
    'ST PAUL': {'ST.PAUL', 'ST. PAUL', 'ST PAUL'},
    'STEGER': {'STEGER', 'STERGER', 'STEGAR'},
    'STICKNEY': {'STICKNEY'},
    'STONE MOUNTAIN': {'STONE MOUNTAIN'},
    'STONE PARK': {'STONE PARK'},
    'STREAMWOOD': {'STREAMWOOD'},
    'STREATOR': {'STREATOR'},
    'STUART': {'STUART'},
    'SUGARLAND': {'SUGARLAND'},
    'SUMMIT': {'SUMMIT'},
    'SUN PRAIRIE': {'SUN PRAIRIE'},
    'TARPON SPRING': {'TARPON SPRING'},
    'TINLET PK': {'TINLET PK'},
    'TINLEY PARK': {'TINLEY PARK', 'TINLY PARK', 'TINLEY  PK.'},
    'TOLEDO': {'TOLEDO'},
    'TORONTO': {'TORONTO'},
    'TUCSON': {'TUCSON'},
    'UNION CITY': {'UNION CITY'},
    'UNIVERSITY PARK': {'UNIVERSAL PARK', 'UNIVERSITY PARK'},
    'URBANA': {'URBANA', 'URBANNA'},
    'VALPARAISO': {'VALPARAISO'},
    'VILLA PARK': {'VILLA PARK', 'VILLA PK'},
    'WASEEKA': {'WASEEKA', 'WASECA'},
    'WASHINGTON': {'WASHINGTON'},
    'WAUKEGAN': {'WAUKEGAN'},
    'WAUSSAU': {'WAUSSAU'},
    'WEBSTER GROVE': {'WEBSTER GROVE'},
    'WEST CHICAGO': {'WEST CHICAGO'},
    'WEST COVINA': {'WEST COVINA'},
    'WEST PALM BEACH': {'WEST PALM BEACH'},
    'WESTCHESTER': {'WESTCHESTER', 'WESTECHESTER'},
    'WESTMONT': {'WESTMONT'},
    'WHEATON': {'WHEATON'},
    'WHEELING': {'WHEELING'},
    'WHITING': {'WHITING', 'WHITTING'},
    'WICHITA': {'WICHITA'},
    'WILLING': {'WILLING'},
    'WILLOW SPRINGS': {'WILOW  SPRINGS', 'WILLOWSPRINGS', 'WILLOW SPRINGS'},
    'WILLOWBROOK': {'WILLOWBROOK'},
    'WILMETTE': {'WILMETTE'},
    'WILMINGTON': {'WILLINGTON', 'WILMINGTON'},
    'WILWOOD': {'WILWOOD'},
    'WOOD DALE': {'WOODDALE', 'WOODALE'},
    'WOODRIDGE': {'WOODRIDGE'},
    'WOODSTOCK': {'WOODSTOCK'},
    'WORTH': {'WORTH'},
    'ZION': {'ZION'}}

gender_dict = None

disp_dict = None

charge_class_dict = None

charge_desc_dict = None

statute_dict = None

bonded_out = [
    'BOND PAID',
    'BOND PAID WITH ELECTRONIC MONITORING',
    'EMI BOND',
    'I BOND',
    'I BOND WITH ELECTRONIC MONITORING'
    ]

awaiting_trial = [
    'CASE CONTINUED',
    'CASE PENDING'
    ]

case_disp = {
    'BOND PAID': 7,
    'BOND PAID WITH ELECTRONIC MONITORING': 7,
    'CASE CONTINUED': 4,
    'CASE DROPPED FOR WANT OF PROSECUTION': 7,
    'CASE PENDING': 4,
    'DEFENDANT EXAMINED AND DISCHARGED': 7,
    'DISCHARGED PER COURT ORDER': 7,
    'DISMISSED': 7,
    'DROPPED': 7,
    'EM AWOL': 1,
    'EMI BOND': 7,
    'FOUND UNFIT TO STAND TRIAL': 6,
    'I BOND': 7,
    'I BOND WITH ELECTRONIC MONITORING': 7,
    'JOINED CASE': 7,
    'NO PROBABLE CAUSE': 7,
    'NO SUIT': 7,
    'NOLLE': 7,
    'NOT GUILTY': 7,
    'OFF CALL': 7,
    'PROBATION': 1,
    'PROBATION TERMINATED SATISFACTORY': 1,
    'PROBATION TERMINATION UNSATISFACT.': 1,
    'PROBATION WITH TASC': 1,
    'SAME BOND TO STAND': 7,
    'SENTENCE EXPIRED': 7,
    'SENTENCED COUNTY TIME': 1,
    'SENTENCED SUPERVISION': 7,
    'SENTENCED TO BOOT CAMP': 1,
    'SENTENCED TO STATE (IDOC)': 1,
    'SENTENCED TO VRIC': 1,
    'SHIP TO IDOC': 1,
    'STRICKEN WITH LEAVE TO REINSTATE': 7,
    'SUPERVISION TERMINATED UNSATISFACTORY': 1,
    'TIME CONSIDERED SERVED': 7,
    'UNKNOWN': 8,
    'VACATED': 7,
    'WARRANT': 5}